<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

namespace GPBMetadata;

class Hello
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aae010a0b68656c6c6f2e70726f746f120e6c6f74746572797365727669" .
            "6365221b0a0a6c6f7474657279526571120d0a05706172616d1801200128" .
            "09221a0a0a6c6f7474657279526573120c0a046461746118012001280932" .
            "4e0a074772656574657212430a076c6f7474657279121a2e6c6f74746572" .
            "79736572766963652e6c6f74746572795265711a1a2e6c6f747465727973" .
            "6572766963652e6c6f74746572795265732200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

